/*
	This file is part of solidity.

	solidity is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	solidity is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
*/
// SPDX-License-Identifier: GPL-3.0

#include "SolidityOps.h"
#include "SolidityDialect.h"

#ifdef SOLIDITY_HAS_MLIR
// Disable warnings for LLVM/MLIR headers
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wconversion"
#include "mlir/IR/Builders.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#pragma GCC diagnostic pop

// Include the generated operation definitions from TableGen
#define GET_OP_CLASSES
#include "SolidityOps.cpp.inc"

// TypeIDs are now defined by TableGen in the included file above

namespace mlir {
namespace solidity {

//===----------------------------------------------------------------------===//
// Custom builders and verifiers for operations
//===----------------------------------------------------------------------===//

// Custom builder for ConstantOp - needed for MLIRGenerator
void ConstantOp::build(mlir::OpBuilder &builder, mlir::OperationState &state,
                       mlir::Attribute value, mlir::Type type) {
	state.addAttribute("value", value);
	state.addTypes(type);
}

// Custom printer for ConstantOp - required due to hasCustomAssemblyFormat
void ConstantOp::print(mlir::OpAsmPrinter &p) {
	p << " ";
	// getValue() is generated by TableGen from the 'value' attribute
	if (auto valueAttr = (*this)->getAttrOfType<mlir::Attribute>("value"))
		p.printAttribute(valueAttr);
	p << " : ";
	p.printType(getResult().getType());
}

// Custom parser for ConstantOp - required due to hasCustomAssemblyFormat
mlir::ParseResult ConstantOp::parse(mlir::OpAsmParser &parser,
                                    mlir::OperationState &result) {
	mlir::Attribute value;
	mlir::Type type;
	
	if (parser.parseAttribute(value, "value", result.attributes) ||
	    parser.parseColon() ||
	    parser.parseType(type))
		return mlir::failure();
	
	result.addTypes(type);
	return mlir::success();
}

// Custom builder for LoadStateVarOp - commented out as TableGen generates this
// void LoadStateVarOp::build(mlir::OpBuilder &builder, mlir::OperationState &state,
//                            mlir::Type resultType, llvm::StringRef varName) {
// 	state.addAttribute("varName", builder.getStringAttr(varName));
// 	state.addTypes(resultType);
// }

// Custom builder for AddOp - commented out as TableGen generates this
// void AddOp::build(mlir::OpBuilder &builder, mlir::OperationState &state,
//                   mlir::Type resultType, mlir::Value lhs, mlir::Value rhs) {
// 	state.addOperands({lhs, rhs});
// 	state.addTypes(resultType);
// }

} // namespace solidity
} // namespace mlir

#else // SOLIDITY_HAS_MLIR

// Empty implementation when MLIR is not available

#endif // SOLIDITY_HAS_MLIR