/*
	This file is part of solidity.

	solidity is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	solidity is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with solidity.  If not, see <http://www.gnu.org/licenses/>.
*/
// SPDX-License-Identifier: GPL-3.0
/**
 * Operation implementations of the `yul` MLIR dialect.
 */

#include "YulOps.h"
#include "YulDialect.h"

// Disable warnings for LLVM/MLIR headers
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wconversion"
#include "llvm/ADT/APInt.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/TypeUtilities.h"
#pragma GCC diagnostic pop

using namespace mlir;
using namespace mlir::yul;

// Generated operation definitions.
#define GET_OP_CLASSES
#include "YulOps.cpp.inc"

//===----------------------------------------------------------------------===//
// ConstOp
//===----------------------------------------------------------------------===//

mlir::OpFoldResult ConstOp::fold(FoldAdaptor)
{
	return getValueAttr();
}

// Note: FuncOp's (name, type) builder is auto-generated by tablegen on this
// LLVM version (attribute-only ops get a convenience builder that also adds
// the body region).
